apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ajsutton/k8s.git
    path: charts/victoria-metrics
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
