argo-cd:
  configs:
    cm:
      params:
        server.insecure: true
  global:
    domain: big
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    service:
      servicePortHttp: 9003
    ingress:
      enabled: true
      ingressClassName: nginx
      tls: false
