argo-cd:
  configs:
    params:
      server.insecure: true
  global:
    domain: big
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    service:
      servicePortHttp: 8082
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      tls: false
      extraHosts:
        - name: big.local
          path: /
    extraArgs:
      - --insecure
