argo-cd:
  configs:
    params:
      server.insecure: true
      server.basehref: "/argocd/"
      server.rootpath: "/argocd/"
  global:
    domain: big
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    ingress:
      enabled: true
      ingressClassName: public
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      path: "/argocd/"
      tls: false
    extraArgs:
      - --insecure
