argo-cd:
  configs:
    params:
      server.insecure: true
  global:
    domain: big
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    service:
      servicePortHttp: 8082
    ingress:
      enabled: true
      tls: false
