argo-cd:
  configs:
    cm:
      params:
        server.insecure: true
  global:
    domain: big
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    ingress:
      enabled: true
      ingressClassName: public
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      tls: false
